// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aqxuelubgsmfmnfinmoj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFxeHVlbHViZ3NtZm1uZmlubW9qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczMDkxMTksImV4cCI6MjA2Mjg4NTExOX0.t7gFZwAUvxALBPhJqWDImWSinoOvbF3lShkrbnxhr_w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);